# Generated by Django 4.2.2 on 2023-06-16 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
    ]
